### ISSUE TITLE
Feature request: allow gosh to be run in a subdir

### ISSUE THREAD

**Issue by riotbib** [oxzi/gosh#24]
Hi @oxzi, would a change to the source to allow gosh to be run in a sub directory be possible? Thanks.

**Comment by riotbib** [comment]
Thanks for your reply.

Yes, I meant the latter. Excuse me confusing the terms.

Would this feature be hard to implement?

**Comment by oxzi** [comment]
Should be a quick patch and I will try to get to this one the other day. Feel free to ping me if this is still open in one or two months.

**Comment by oxzi** [comment]
@riotbib: Please feel free to test the recently pushed changes. By
adding `-url-prefix /gosh` you should be able to host a gosh under the
`/gosh` path.

**Comment by riotbib** [comment]
Works fine. Thanks a lot, @oxzi!
