### ISSUE TITLE
Response too long ( ͡° ͜ʖ ͡°)

### ISSUE THREAD

**Issue by riotbib** [oxzi/gosh#6]
The response output by the HTTP server is too long in some cases.
It prints several lines, which does not come handy, if you want to use it with WeeChat-Android for example.

Could you implement a flag or header which may be sent to get a one-line response with just the URL for viewing?

Thanks for all your work! (✿◠‿◠)

**Comment by oxzi** [comment]
> Thanks for all your work! (✿◠‿◠)

(´ω｀*)
